Repeated incorrect input in C checks, resolves #2
minprog/cs50x pull request #26
Opened 2019-10-25 10:20 UTC by bjorn-out

Resolves #2. Draft request because greedy is untested, as I don't have example code to run it on at the moment.

2019-10-28 21:34 UTC, bjorn-out commented
Tested, works.

2019-10-30 18:05 UTC, stgm commented
Ik ben niet zo'n fan van de "twice" hint in de test-omschrijvingen. Drie keer moet ook afgevangen worden.

Ik zou zelf zeggen dat er een aparte test moet komen "rejects any number of invalid inputs". Hierin moet (met een loop) zó vaak een ongeldige input worden gegeven dat het belachelijk wordt als een student het zonder loop oplost. Mocht dat dan toch gebeuren, dan heeft de assistent een mooi feedbackpunt.

2019-10-30 23:17 UTC, bjorn-out commented
Seems good. I can't go really crazy with the C checks, as it would slow down checking too much. Around 15 is probably more than enough though. Also added this for the py checks (which does run a stupid amount of times)

2019-10-31 11:06 UTC, stgm commented
Lijkt mij mooi, @Jelleas nog een korte technische review?

2019-11-01 16:33 UTC, Jelleas requested changes

2019-11-01 16:33 UTC, Jelleas commented on credit/__init__.py
> +    for i in range(8):
Is het echt nodig om dit x8 te doen? Kost behoorlijk wat tijd?

2019-11-01 16:33 UTC, Jelleas commented on mario/less/__init__.py
> +    for i in range(5):
Ditto

2019-11-01 16:33 UTC, Jelleas commented on greedy/__init__.py
> +    for i in range(5):
Ditto

2019-11-01 16:33 UTC, Jelleas commented on py/mario/__init__.py
> +    check_pyramid(result.stdout, ("Height: " * 177) + open("2.txt").read())
`* len(values)`? i.p.v. `* 177`

2019-11-01 16:33 UTC, Jelleas commented on py/mario/__init__.py
> +    values = list(range(-100, 0)) + list(range(24, 100)) + ["2"]
Is zoveel input echt nodig? Maakt het lastig te debuggen.

2019-11-01 16:33 UTC, Jelleas commented on py/greedy/__init__.py
> +    values = list(range(-100, 0)) + ["foo", "bar", "baz", "lorem", "ipsum", "dolor", "sit", "amet", "2"]
Is zoveel input echt nodig? Maakt het lastig te debuggen.

2019-11-01 16:40 UTC, bjorn-out commented on credit/__init__.py
> +    for i in range(8):
Dat is niet écht nodig, maar het moest genoeg zijn dat het te gek zou zijn om er met if-statements omheen te komen. Is 3 keer (in totaal dus 6 inputs) ook voldoende?

2019-11-01 17:59 UTC, stgm commented
@Jelleas Aangezien het om al die dingen gaat reageer ik even hier. Hoeveel tijd kost dat dan? Ik wil wel graag een keer of 8 zodat het bij het nakijken echt opvalt als mensen hier geen loop gebruiken (en beter: dat ze voor die tijd zelf op het idee komen dat het niet werkt zo - dat is bij 3x een stuk minder zeker).

2019-11-02 10:49 UTC, Jelleas commented
`reject()` kijkt of het programma na X aantal seconden nog draait. Dus zestien keer `reject()` aanroepen met een timeout van 1 seconde, betekent dus 16 seconden langer. 

Mischien is dit een idee, vul wel zestien keer foute input in, maar roep reject maar één keer aan het einde aan? Dat bereikt effectief hetzelfde, maar maakt het wel veel sneller.

2019-11-04 11:27 UTC, stgm commented
Weer wat geleerd ;-) Lijkt me prima?

2019-11-04 23:16 UTC, bjorn-out commented
Goed idee, inderdaad. Het is aangepast.

2019-11-06 11:42 UTC, merged